# Generated by Django 6.0.3 on 2026-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maratona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['data', 'nome'],
            },
        ),
    ]
