# Generated by Django 6.0.3 on 2026-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0002_refatora_campos_maratona'),
    ]

    operations = [
        migrations.AddField(
            model_name='maratona',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='maratonas/'),
        ),
    ]
