# Generated by Django 6.0.3 on 2026-06-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0003_maratona_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maratona',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='maratonas/'),
        ),
    ]
