# Generated by Django 6.0.3 on 2026-06-14 20:34

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0006_sanitiza_distancias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='maratona',
            constraint=models.CheckConstraint(condition=models.Q(('distancia__gte', Decimal('0.01')), ('distancia__lte', Decimal('999.99'))), name='maratona_distancia_valida'),
        ),
    ]
